#!/bin/bash
# cli/doctor.sh — nexus doctor

cmd_doctor() {
  # Disable set -e for doctor — we handle errors ourselves
  set +e

  local quick=false
  local fix=false

  for arg in "$@"; do
    case "$arg" in
      --quick) quick=true ;;
      --fix)   fix=true ;;
    esac
  done

  if [ ! -d ".git" ]; then
    echo ""
    echo -e "  ${RED}Not a git repository.${NC} Run nexus doctor from inside a project."
    echo ""
    return 1
  fi

  echo ""
  echo -e "  ${BOLD}nexus doctor${NC}"
  echo ""

  local passed=0
  local failed=0
  local skipped=0

  # ── 1. CLAUDE.md file structure sync ─────────────────────────────
  if [ -f "CLAUDE.md" ] && grep -q "nexus:file-structure" "CLAUDE.md" 2>/dev/null && [ -f "scripts/sync-claude-md.sh" ]; then
    local backup="CLAUDE.md.doctor-backup"
    cp "CLAUDE.md" "$backup"
    bash scripts/sync-claude-md.sh 2>/dev/null || true
    if diff -q "$backup" "CLAUDE.md" > /dev/null 2>&1; then
      print_ok "CLAUDE.md file structure"
      ((passed++)) || true
    else
      if $fix; then
        print_ok "CLAUDE.md file structure ${DIM}(fixed)${NC}"
        ((passed++)) || true
      else
        cp "$backup" "CLAUDE.md"
        print_fail "CLAUDE.md file structure out of sync"
        echo -e "        ${DIM}Run: nexus doctor --fix${NC}"
        ((failed++)) || true
      fi
    fi
    rm -f "$backup"
  else
    print_skip "CLAUDE.md file structure"
    ((skipped++)) || true
  fi

  # ── 2. .env.example coverage ─────────────────────────────────────
  if [ -f "scripts/check-env-sync.sh" ]; then
    local env_output
    env_output=$(bash scripts/check-env-sync.sh 2>&1)
    local env_exit=$?
    if [ $env_exit -eq 0 ]; then
      print_ok ".env.example coverage"
      ((passed++)) || true
    else
      if $fix && [ -f ".env.example" ]; then
        echo "$env_output" | grep "^  " | tr -d ' ' | while IFS= read -r varname; do
          [ -n "$varname" ] && echo "${varname}= # TODO: set value" >> ".env.example"
        done
        print_ok ".env.example coverage ${DIM}(fixed)${NC}"
        ((passed++)) || true
      else
        print_fail ".env.example coverage"
        echo "$env_output" | head -3 | while IFS= read -r line; do
          echo -e "        ${DIM}${line}${NC}"
        done
        ((failed++)) || true
      fi
    fi
  elif $fix && [ ! -f ".env.example" ]; then
    # Create .env.example from code references
    echo "# Auto-generated by nexus doctor --fix" > .env.example
    grep -roh 'process\.env\.\([A-Z_][A-Z0-9_]*\)' --include='*.ts' --include='*.tsx' --include='*.js' . 2>/dev/null \
      | sed 's/process\.env\.//' | sort -u | while IFS= read -r var; do
        echo "${var}=" >> .env.example
      done
    print_ok ".env.example ${DIM}(created)${NC}"
    ((passed++)) || true
  else
    print_skip ".env.example coverage"
    ((skipped++)) || true
  fi

  # ── 3. Dependency direction ──────────────────────────────────────
  if has_cmd bun && [ -f "scripts/check-deps-direction.ts" ]; then
    local deps_output
    deps_output=$(bun scripts/check-deps-direction.ts 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Dependency direction"
      ((passed++)) || true
    else
      print_fail "Dependency direction"
      echo "$deps_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  else
    print_skip "Dependency direction"
    ((skipped++)) || true
  fi

  # ── 4. Hallucinated imports ──────────────────────────────────────
  if has_cmd bun && [ -f "scripts/check-hallucinated-imports.ts" ]; then
    local hall_output
    hall_output=$(bun scripts/check-hallucinated-imports.ts 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Hallucinated imports"
      ((passed++)) || true
    else
      print_fail "Hallucinated imports"
      echo "$hall_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  else
    print_skip "Hallucinated imports"
    ((skipped++)) || true
  fi

  # ── 5. Dead exports (skip if --quick) ────────────────────────────
  if $quick; then
    : # silent skip
  elif has_cmd bun && [ -f "scripts/check-dead-exports.ts" ]; then
    local dead_output
    dead_output=$(bun scripts/check-dead-exports.ts 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Dead exports"
      ((passed++)) || true
    else
      print_fail "Dead exports"
      echo "$dead_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  else
    if ! $quick; then print_skip "Dead exports"; ((skipped++)) || true; fi
  fi

  # ── 6. Orphaned files (skip if --quick) ──────────────────────────
  if $quick; then
    : # silent skip
  elif has_cmd bun && [ -f "scripts/check-orphaned-files.ts" ]; then
    local orph_output
    orph_output=$(bun scripts/check-orphaned-files.ts 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Orphaned files"
      ((passed++)) || true
    else
      print_fail "Orphaned files"
      echo "$orph_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  else
    if ! $quick; then print_skip "Orphaned files"; ((skipped++)) || true; fi
  fi

  # ── 7. Nexus version (skip if --quick) ───────────────────────────
  if $quick; then
    : # silent skip
  elif [ -f "$HOME/.nexus/VERSION" ]; then
    local local_ver
    local_ver=$(cat "$HOME/.nexus/VERSION" 2>/dev/null || echo "unknown")
    git -C "$HOME/.nexus" fetch --quiet origin main 2>/dev/null || true
    local remote_ver
    remote_ver=$(git -C "$HOME/.nexus" show origin/main:VERSION 2>/dev/null || echo "")
    if [ -z "$remote_ver" ] || [ "$local_ver" = "$remote_ver" ]; then
      print_ok "Nexus v${local_ver}"
      ((passed++)) || true
    else
      print_fail "Nexus outdated (v${local_ver} → v${remote_ver})"
      echo -e "        ${DIM}Run: curl -fsSL https://www.teonnaise.com/install | bash${NC}"
      ((failed++)) || true
    fi
  else
    if ! $quick; then print_skip "Nexus version"; ((skipped++)) || true; fi
  fi

  # ── Summary ──────────────────────────────────────────────────────
  local total=$((passed + failed))
  echo ""
  if [ $failed -eq 0 ] && [ $total -gt 0 ]; then
    echo -e "  ${GREEN}${passed}/${total} passed${NC}  ${DIM}${skipped} skipped${NC}"
  elif [ $total -gt 0 ]; then
    echo -e "  ${passed}/${total} passed  ${RED}${failed} failed${NC}  ${DIM}${skipped} skipped${NC}"
  fi

  # ── Recommendations ──────────────────────────────────────────────
  if ! $quick; then
    local recs=0
    local rec_lines=""

    # No linter
    if [ -f "package.json" ] && ! grep -q '"eslint"\|"biome"\|"@biomejs"' package.json 2>/dev/null; then
      rec_lines="${rec_lines}   ~  No linter. Run: pnpm add -D eslint\n"
      ((recs++)) || true
    fi

    # TypeScript strict off
    if [ -f "tsconfig.json" ] && ! grep -q '"strict":\s*true' tsconfig.json 2>/dev/null; then
      rec_lines="${rec_lines}   ~  TypeScript strict mode is off\n"
      ((recs++)) || true
    fi

    # No formatter
    if [ -f "package.json" ] && ! ls .prettierrc* biome.json 2>/dev/null | grep -q .; then
      rec_lines="${rec_lines}   ~  No formatter. Run: pnpm add -D prettier\n"
      ((recs++)) || true
    fi

    # No test runner
    if [ -f "package.json" ] && ! grep -q '"vitest"\|"jest"\|"playwright"\|"@testing-library"' package.json 2>/dev/null; then
      rec_lines="${rec_lines}   ~  No test runner. Run: pnpm add -D vitest\n"
      ((recs++)) || true
    fi

    # No pre-commit hooks
    if [ ! -f "lefthook.yml" ] && [ ! -d ".husky" ]; then
      rec_lines="${rec_lines}   ~  No pre-commit hooks. Run: nexus init\n"
      ((recs++)) || true
    fi

    # No CLAUDE.md
    if [ ! -f "CLAUDE.md" ]; then
      rec_lines="${rec_lines}   ~  No CLAUDE.md. Run: nexus init\n"
      ((recs++)) || true
    fi

    # No .env.example
    if [ ! -f ".env.example" ] && [ -f "package.json" ]; then
      rec_lines="${rec_lines}   ~  No .env.example. Run: nexus doctor --fix\n"
      ((recs++)) || true
    fi

    # No engines field
    if [ -f "package.json" ] && ! grep -q '"engines"' package.json 2>/dev/null; then
      rec_lines="${rec_lines}   ~  No engines field in package.json. Pin your Node version.\n"
      ((recs++)) || true
    fi

    # CommonJS
    if [ -f "package.json" ] && ! grep -q '"type":\s*"module"' package.json 2>/dev/null && [ -f "package.json" ]; then
      rec_lines="${rec_lines}   ~  No \"type\": \"module\" in package.json\n"
      ((recs++)) || true
    fi

    if [ $recs -gt 0 ]; then
      echo ""
      echo -e "  ${BOLD}Recommendations${NC}"
      printf "$rec_lines"
      echo ""
      echo -e "  ${DIM}${recs} recommendation(s)${NC}"
    fi
  fi

  echo ""
  return $failed
}
