#!/bin/bash
# cli/doctor.sh — nexus doctor (detection-aware)

cmd_doctor() {
  set +e

  local quick=false
  local fix=false

  for arg in "$@"; do
    case "$arg" in
      --quick) quick=true ;;
      --fix)   fix=true ;;
    esac
  done

  if [ ! -d ".git" ]; then
    echo ""
    echo -e "  ${RED}Not a git repository.${NC} Run nexus doctor from inside a project."
    echo ""
    return 1
  fi

  local eco
  eco=$(detect_ecosystem)

  echo ""
  echo -e "  ${BOLD}nexus doctor${NC}"
  echo ""

  local passed=0
  local failed=0

  # ── 1. CLAUDE.md file structure sync (all ecosystems) ───────────
  if [ -f "CLAUDE.md" ] && grep -q "nexus:file-structure" "CLAUDE.md" 2>/dev/null; then
    local backup
    backup=$(mktemp)
    cp "CLAUDE.md" "$backup"
    bash "$HOME/.nexus/scripts/sync-claude-md.sh" > /dev/null 2>&1 || true
    if diff -q "$backup" "CLAUDE.md" > /dev/null 2>&1; then
      print_ok "CLAUDE.md file structure"
      ((passed++)) || true
    else
      if $fix; then
        print_ok "CLAUDE.md file structure ${DIM}(fixed)${NC}"
        ((passed++)) || true
      else
        cp "$backup" "CLAUDE.md"
        print_fail "CLAUDE.md file structure out of sync"
        echo -e "        ${DIM}Run: nexus doctor --fix${NC}"
        ((failed++)) || true
      fi
    fi
    rm -f "$backup"
  elif $fix && [ ! -f "CLAUDE.md" ] && [ -f "$TEMPLATES/CLAUDE.md" ]; then
    cp "$TEMPLATES/CLAUDE.md" "CLAUDE.md"
    if [ "$eco" = "node" ] && [ -f "$TEMPLATES/CLAUDE.md.node" ]; then
      printf "\n" >> "CLAUDE.md"
      cat "$TEMPLATES/CLAUDE.md.node" >> "CLAUDE.md"
    fi
    print_ok "CLAUDE.md ${DIM}(created)${NC}"
    ((passed++)) || true
  elif [ -f "CLAUDE.md" ]; then
    print_ok "CLAUDE.md file structure"
    ((passed++)) || true
  else
    print_fail "No CLAUDE.md"
    echo -e "        ${DIM}Run: nexus init${NC}"
    ((failed++)) || true
  fi

  # ── 2. .env.example coverage (ecosystems with env patterns) ─────
  if [ "$eco" != "generic" ]; then
    if $fix && [ ! -f ".env.example" ]; then
      echo "# Auto-generated by nexus doctor --fix" > .env.example
      grep -roEh '(process\.env|Bun\.env)\.[A-Z_][A-Z0-9_]*' --include='*.ts' --include='*.tsx' --include='*.js' . 2>/dev/null \
        | sed -E 's/(process\.env|Bun\.env)\.//' | sort -u | while IFS= read -r var; do
          echo "${var}=" >> .env.example
        done
      print_ok ".env.example ${DIM}(created)${NC}"
      ((passed++)) || true
    elif [ -f "$HOME/.nexus/scripts/check-env-sync.sh" ]; then
      local env_output
      env_output=$(bash "$HOME/.nexus/scripts/check-env-sync.sh" 2>&1)
      local env_exit=$?
      if [ $env_exit -eq 0 ]; then
        print_ok ".env.example coverage"
        ((passed++)) || true
      else
        if $fix && [ -f ".env.example" ]; then
          echo "$env_output" | grep "^  - " | sed 's/^  - //' | while IFS= read -r varname; do
            [ -n "$varname" ] && echo "${varname}= # TODO: set value" >> ".env.example"
          done
          print_ok ".env.example coverage ${DIM}(fixed)${NC}"
          ((passed++)) || true
        else
          print_fail ".env.example coverage"
          echo "$env_output" | head -3 | while IFS= read -r line; do
            echo -e "        ${DIM}${line}${NC}"
          done
          ((failed++)) || true
        fi
      fi
    fi
  fi

  # ── 3. Dependency direction (Node only) ─────────────────────────
  if [ "$eco" = "node" ] && has_cmd bun && [ -f "$HOME/.nexus/scripts/check-deps-direction.ts" ]; then
    local deps_output
    deps_output=$(bun "$HOME/.nexus/scripts/check-deps-direction.ts" 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Dependency direction"
      ((passed++)) || true
    else
      print_fail "Dependency direction"
      echo "$deps_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  fi

  # ── 4. Hallucinated imports (Node only) ─────────────────────────
  if [ "$eco" = "node" ] && has_cmd bun && [ -f "$HOME/.nexus/scripts/check-hallucinated-imports.ts" ]; then
    local hall_output
    hall_output=$(bun "$HOME/.nexus/scripts/check-hallucinated-imports.ts" 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Hallucinated imports"
      ((passed++)) || true
    else
      print_fail "Hallucinated imports"
      echo "$hall_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  fi

  # ── 5. Dead exports (Node only, skip if --quick) ────────────────
  if ! $quick && [ "$eco" = "node" ] && has_cmd bun && [ -f "$HOME/.nexus/scripts/check-dead-exports.ts" ]; then
    local dead_output
    dead_output=$(bun "$HOME/.nexus/scripts/check-dead-exports.ts" 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Dead exports"
      ((passed++)) || true
    else
      print_fail "Dead exports"
      echo "$dead_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  fi

  # ── 6. Orphaned files (Node only, skip if --quick) ──────────────
  if ! $quick && [ "$eco" = "node" ] && has_cmd bun && [ -f "$HOME/.nexus/scripts/check-orphaned-files.ts" ]; then
    local orph_output
    orph_output=$(bun "$HOME/.nexus/scripts/check-orphaned-files.ts" 2>&1)
    if [ $? -eq 0 ]; then
      print_ok "Orphaned files"
      ((passed++)) || true
    else
      print_fail "Orphaned files"
      echo "$orph_output" | head -5 | while IFS= read -r line; do
        echo -e "        ${DIM}${line}${NC}"
      done
      ((failed++)) || true
    fi
  fi

  # ── 7. Nexus version (skip if --quick) ──────────────────────────
  if ! $quick && [ -f "$HOME/.nexus/VERSION" ]; then
    local local_ver
    local_ver=$(cat "$HOME/.nexus/VERSION" 2>/dev/null || echo "unknown")
    git -C "$HOME/.nexus" fetch --quiet origin main 2>/dev/null || true
    local remote_ver
    remote_ver=$(git -C "$HOME/.nexus" show origin/main:VERSION 2>/dev/null || echo "")
    if [ -z "$remote_ver" ] || [ "$local_ver" = "$remote_ver" ]; then
      print_ok "Nexus v${local_ver}"
      ((passed++)) || true
    else
      print_fail "Nexus outdated (v${local_ver} → v${remote_ver})"
      echo -e "        ${DIM}Run: curl -fsSL https://www.teonnaise.com/install | bash${NC}"
      ((failed++)) || true
    fi
  fi

  # ── Fix: drop missing infrastructure ────────────────────────────
  if $fix; then
    if [ ! -f "lefthook.yml" ] && [ -f "$TEMPLATES/lefthook.yml" ]; then
      cp "$TEMPLATES/lefthook.yml" "lefthook.yml"
      if [ "$eco" = "node" ] && [ -f "$TEMPLATES/lefthook.yml.node" ]; then
        cat "$TEMPLATES/lefthook.yml.node" >> "lefthook.yml"
      fi
      if has_cmd lefthook; then
        lefthook install > /dev/null 2>&1 || true
      fi
      echo -e "  ${GREEN}created${NC} lefthook.yml"
    fi
  fi

  # ── Summary ──────────────────────────────────────────────────────
  local total=$((passed + failed))
  echo ""
  if [ $failed -eq 0 ] && [ $total -gt 0 ]; then
    echo -e "  ${GREEN}${passed}/${total} passed${NC}"
  elif [ $total -gt 0 ]; then
    echo -e "  ${passed}/${total} passed  ${RED}${failed} failed${NC}"
  fi

  # ── Recommendations (skip if --quick) ───────────────────────────
  if ! $quick; then
    local recs=0
    local rec_lines=""

    # Universal recommendations
    if [ ! -f "CLAUDE.md" ]; then
      rec_lines="${rec_lines}   ~  No CLAUDE.md. Run: nexus init\n"
      ((recs++)) || true
    fi

    if [ ! -f "lefthook.yml" ] && [ ! -d ".husky" ]; then
      rec_lines="${rec_lines}   ~  No pre-commit hooks. Run: nexus init\n"
      ((recs++)) || true
    fi

    if [ ! -f ".env.example" ] && [ "$eco" != "generic" ]; then
      rec_lines="${rec_lines}   ~  No .env.example. Run: nexus doctor --fix\n"
      ((recs++)) || true
    fi

    # Node-specific recommendations
    if [ "$eco" = "node" ] && [ -f "package.json" ]; then
      if ! grep -qE '"eslint"|"biome"|"@biomejs"' package.json 2>/dev/null; then
        rec_lines="${rec_lines}   ~  No linter. Run: pnpm add -D eslint\n"
        ((recs++)) || true
      fi

      if [ -f "tsconfig.json" ] && ! grep -qE '"strict":\s*true' tsconfig.json 2>/dev/null; then
        rec_lines="${rec_lines}   ~  TypeScript strict mode is off\n"
        ((recs++)) || true
      fi

      if ! ls .prettierrc* biome.json 2>/dev/null | grep -q .; then
        rec_lines="${rec_lines}   ~  No formatter. Run: pnpm add -D prettier\n"
        ((recs++)) || true
      fi

      if ! grep -qE '"vitest"|"jest"|"playwright"|"@testing-library"' package.json 2>/dev/null; then
        rec_lines="${rec_lines}   ~  No test runner. Run: pnpm add -D vitest\n"
        ((recs++)) || true
      fi

      if ! grep -q '"engines"' package.json 2>/dev/null; then
        rec_lines="${rec_lines}   ~  No engines field in package.json\n"
        ((recs++)) || true
      fi

      if ! grep -qE '"type":\s*"module"' package.json 2>/dev/null; then
        rec_lines="${rec_lines}   ~  No \"type\": \"module\" in package.json\n"
        ((recs++)) || true
      fi
    fi

    if [ $recs -gt 0 ]; then
      echo ""
      echo -e "  ${BOLD}Recommendations${NC}"
      printf "$rec_lines"
      echo ""
      echo -e "  ${DIM}${recs} recommendation(s)${NC}"
    fi
  fi

  # ── Write health to .nexus/.last-doctor ─────────────────────────
  mkdir -p .nexus
  local now
  now=$(date -u +"%Y-%m-%dT%H:%M:%S")
  echo "- Last doctor: ${now}" > .nexus/.last-doctor
  echo "- Result: ${passed}/${total} passed${failed:+, ${failed} failed}" >> .nexus/.last-doctor
  if [ -n "${rec_lines:-}" ]; then
    local clean_recs
    clean_recs=$(printf '%b' "$rec_lines" | sed 's/^   ~  //' | sed "s/\x1b\[[0-9;]*m//g" | paste -sd', ' -)
    echo "- Recommendations: ${clean_recs}" >> .nexus/.last-doctor
  fi

  echo ""
  return $failed
}
