#!/usr/bin/env bash
# sync-claude-md.sh
# Regenerates the file structure section in CLAUDE.md between
# <!-- nexus:file-structure --> and <!-- nexus:end --> markers.
# Also supports v1 legacy markers (FILE_STRUCTURE_START/END).

set -euo pipefail

CLAUDE_MD="${1:-CLAUDE.md}"

if [[ ! -f "$CLAUDE_MD" ]]; then
  echo "sync-claude-md: $CLAUDE_MD not found, skipping." >&2
  exit 0
fi

# Check for required markers (support both v2 nexus markers and v1 legacy markers)
if grep -q "nexus:file-structure" "$CLAUDE_MD"; then
  MARKER_START="nexus:file-structure"
  MARKER_END="nexus:end"
elif grep -q "FILE_STRUCTURE_START" "$CLAUDE_MD"; then
  MARKER_START="FILE_STRUCTURE_START"
  MARKER_END="FILE_STRUCTURE_END"
else
  echo "sync-claude-md: no file-structure markers found in $CLAUDE_MD, skipping." >&2
  exit 0
fi

# Build the file tree (full file listing, sorted, max 80 lines)
TREE=$(find . \
  -not \( \
    -path "*/node_modules/*" -o \
    -path "*/.git/*" -o \
    -path "*/.next/*" -o \
    -path "*/dist/*" -o \
    -path "*/build/*" -o \
    -path "*/.turbo/*" -o \
    -path "*/coverage/*" -o \
    -path "*/.vercel/*" -o \
    -name ".DS_Store" -o \
    -name "*.tsbuildinfo" \
  \) \
  -print \
  | sort \
  | head -80)

LINE_COUNT=$(printf '%s\n' "$TREE" | wc -l | tr -d ' ')

# Fall back to directory-only view if too many lines
if [[ "$LINE_COUNT" -gt 60 ]]; then
  TREE=$(find . \
    -type d \
    -not \( \
      -path "*/node_modules/*" -o \
      -path "*/.git/*" -o \
      -path "*/.next/*" -o \
      -path "*/dist/*" -o \
      -path "*/build/*" -o \
      -path "*/.turbo/*" -o \
      -path "*/coverage/*" -o \
      -path "*/.vercel/*" \
    \) \
    -print \
    | sort \
    | head -40)
fi

# Write replacement block to a temp file (avoids awk multiline -v issues)
TMPFILE=$(mktemp)
cat > "$TMPFILE" <<BLOCK
<!-- ${MARKER_START} -->
## File Structure
<!-- Auto-generated by scripts/sync-claude-md.sh — do not edit manually -->
\`\`\`
${TREE}
\`\`\`
<!-- ${MARKER_END} -->
BLOCK

# Use awk to replace the content between the markers (inclusive)
# Only replace between the FIRST marker_start and the next marker_end
awk -v ms="$MARKER_START" -v me="$MARKER_END" -v tmpfile="$TMPFILE" '
  !done && $0 ~ ms {
    printing=1
    while ((getline line < tmpfile) > 0) print line
    close(tmpfile)
    next
  }
  printing && $0 ~ me { printing=0; done=1; next }
  printing { next }
  { print }
' "$CLAUDE_MD" > "${CLAUDE_MD}.tmp"

rm -f "$TMPFILE"
mv "${CLAUDE_MD}.tmp" "$CLAUDE_MD"

echo "sync-claude-md: updated file structure in $CLAUDE_MD (${LINE_COUNT} lines)."
